services:
  docker-backup-dev:
    build: .
    image: docker-backup-dev:v1.0.0
    container_name: docker-backup-dev
    volumes:
      # Mount source code for development
      - .:/app
      # Socket Docker to interact with Docker host
      - /var/run/docker.sock:/var/run/docker.sock
      # Cache Composer to speed up installations
      - composer-cache:/root/.composer
      # Mount build directory for testing
      - ./build:/app/build
      # IMPORTANT: Mount host backups directory for testing
      - ./backups:/app/backups
    working_dir: /app
    environment:
      - COMPOSER_CACHE_DIR=/root/.composer
      # Path of the project on the host for Docker-in-Docker volume mapping
      - HOST_PROJECT_DIR=${PWD}
    # Keep container active for development
    tty: true
    stdin_open: true

volumes:
  composer-cache: